### ISSUE TITLE
Linux does not accept multiple arguments in shebang

### ISSUE THREAD

**Issue by salevin** [mzwallace/dw-cli#1]
https://github.com/mzwallace/dw-cli/blob/bfdae79a441708dbe178bff93a2937b70bdd6021/lib/cli.js#L1

My fix is just to replace line with `#!/usr/bin/node --harmony`, but there are issues with that as well.

[See same issue in redux-cli.](https://github.com/SpencerCDixon/redux-cli/issues/42)

**Comment by davidmerrique** [comment]
@salevin It actually seems like we don't need the `--harmony` flag, I don't think we're using any harmony features. 

Would removing that fix the problem for you?

**Comment by salevin** [comment]
Yea that would fix the issue, thanks :+1:
