### ISSUE TITLE
`dw push` throws `The command 'push' is not valid.`

### ISSUE THREAD

**Issue by seanahern** [mzwallace/dw-cli#3]
Hi I'm checking out this CLI for some minimal sandbox build usage. Hoping to get some info about an error thrown for the push command.

### Background
I'm using the `dw push` command to push a new version to a remote sandbox, with something like the following dw-cli.json config:

```
{
  "username": "XXXX@XXXXX.com",
  "password": "XXXXXXXXXXXXXX",

  "cartridges": "tmp",
  "apiVersion": "v16_6",

  "clientId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX",
  "clientPassword": "XXXXXXXXXXXXXXXXXX",

  "instances": {
    "abcd001": {
      "hostname": "xxx.commercecloud.salesforce.com",
      "webdav": "xxx.commercecloud.salesforce.com"
    }
  }
} 
```

`tmp` is used because cartridges are copied from multiple sources. 

**Node version**: Have tried `8.9.1`, as well as `10.15.0`

### Issue
`dw push abcd001` returns this error `The command 'push' is not valid.`. Understood that there's a simple try/catch in place at the moment. I have tried versions with custom version ID appended, as well as cartridge parameter included. I added some logging to the catch in cli.js and found:

```
{ Error: Cannot find module 'cdata/dist/BinaryHeap'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../node_modules/cwait/dist/TaskQueue.js:5:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../node_modules/cwait/dist/index.js:7:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32) code: 'MODULE_NOT_FOUND' }
```
Other commands like `activate`, and `versions` work as expected. 

I also put some logging in the command's actual script and it didn't appear to reaching that point at all. 

**Any ideas as to what would be causing this error?** I'm not sure what to adjust based on this stack trace, as it seems to be a couple layers deep. Thanks!

**Comment by johnnygreen** [comment]
Hello @seanahern!  Sorry for the delay.  Can you confirm which O/S you're using?

**Comment by johnnygreen** [comment]
Ah, nvm, was able to reproduce.  Looking into it!

**Comment by johnnygreen** [comment]
~~Looks like it's tied to Bluebird via cwait ....~~

~~We're going to remove Bluebird as a dep and use native Promise API.  Hope to get v2.0.1 out today or tomorrow.~~

Looks like we are using cwait directly in the push command.  Going to figure out the issue there.

cc @davidmerrique

**Comment by johnnygreen** [comment]
@seanahern patched!  Updated cwait to 1.1.2, worked like a charm.  See v2.0.1.

**Comment by seanahern** [comment]
This fixed it! Thanks @johnnygreen!

**Comment by johnnygreen** [comment]
Great! Thanks for letting us know, @seanahern!
