### ISSUE TITLE
How cartridges property works?

### ISSUE THREAD

**Issue by gbisignano** [mzwallace/dw-cli#4]
Hi, i want to put in the version code, only the cartridges but if I give all path, it push all content.

An example: my project root is 'git' and inside there are all files and cartridges:

-app_abc
-app_abc_controllers
-.gitignore
-gulpfile.js
...
...
...

i want to upload only app_abc, app_abc_controllers, but it upload all.

How i have to do this?

Thank you very much

**Comment by johnnygreen** [comment]
Hi @gbisignano.

Thanks for using the package.  The traditional file structure for SFCC projects has all cartridge related files in their own 'cartridges' folder.  We don't have any configuration setup now to be able to ignore files inside the defined cartridge folder.

A quick fix would be to move your cartridges into their own folder, leaving all build related and misc files one level up.
